name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mpi4py/setup-mpi@v1
      - run: make
      - run: make check

  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Requirements
      run: sudo apt install doxygen
        && sudo apt install python3-sphinx
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build docs
      run: cd doc
        && make html
        && cd _build/html
        && touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: doc/_build/html # The folder the action should deploy.
